### ISSUE TITLE
Three possibly related bugs on TBird contact synching to Google

### ISSUE THREAD

**Issue by saleslogistix** [zanonmark/Google-4-TbSync#12]
All of these bugs are discovered on Tbird 78.10.2 (64 bit--is THAT the problem?) running Google-4-tbSync 0.1.3 and TBsync 2.21 on Windows 10 64bit.
They are all repeatable.  They are all observed with the same contact database (~400) with about 15 labels.
Bug #1: Google Labels not synching with TB List members
When synching, the Google Label names come over to TB's address book, but none of the constituent contacts are populated in TB.

Bug #2: Sync is Deleting new contacts in TBird
I create a new contact in Tbird. I confirm that it is there.
I sync it with Google (which did not have my new contact).
Sync status is now OK.
The new contact in Tbird is totally gone. 

Bug #3: Updates to existing contacts not getting passed to Google
Have an existing contact
Modify record and save it
Confirm that it has been saved
Sync it to Google
Sync status now says OK
Updated data not visible in Google.

I have also reported this to John Beiling, he says it's not his work.

**Comment by saleslogistix** [comment]
Note: all the contacts in the database have email addresses.
Log files are available on request.

**Comment by zanonmark** [comment]
> Tbird 78.10.2 (64 bit--is THAT the problem?)

no, the add-on is cpu-agnostic

> Bug #1: Google Labels not synching with TB List members
> When synching, the Google Label names come over to TB's address book,
> but none of the constituent contacts are populated in TB.

This could be a possible bug since I just observed something similar, and I still have to investigate the issue.

Could You please:
a) disable the account,
b) re-enable it,
c) re-do the synchronization?
All the contacts should populate the groups.

In other words, the issue shouldn't happen when doing the first synchronization, but only on subsequent ones.
Could You please confirm?

> Bug #2: Sync is Deleting new contacts in TBird
> I create a new contact in Tbird. I confirm that it is there.
> I sync it with Google (which did not have my new contact).
> Sync status is now OK.
> The new contact in Tbird is totally gone.

Are You running in read-only mode?

> Bug #3: Updates to existing contacts not getting passed to Google
> Have an existing contact
> Modify record and save it
> Confirm that it has been saved
> Sync it to Google
> Sync status now says OK
> Updated data not visible in Google.

Two questions here:
Are You running in read-only mode?
Which fields did you actually modify?

> I have also reported this to John Beiling, he says it's not his work.

Correct, if they are confirmed it's my job actually :)

Thanks,
MZ

**Comment by saleslogistix** [comment]
> This could be a possible bug since I just observed something similar, and I still have to investigate the issue.
> 
> Could You please:
> a) disable the account,
> b) re-enable it,
> c) re-do the synchronization?
> All the contacts should populate the groups.
> 
> In other words, the issue shouldn't happen when doing the first synchronization, but only on subsequent ones.
> Could You please confirm?
CONFIRMED!
Works fine on initial sync, but after that all the Tbird lists are emptied out.

> > Bug #2: Sync is Deleting new contacts in TBird
> > I create a new contact in Tbird. I confirm that it is there.
> > I sync it with Google (which did not have my new contact).
> > Sync status is now OK.
> > The new contact in Tbird is totally gone.
> 
> Are You running in read-only mode?
No.  
 
> > Bug #3: Updates to existing contacts not getting passed to Google
> > Have an existing contact
> > Modify record and save it
> > Confirm that it has been saved
> > Sync it to Google
> > Sync status now says OK
> > Updated data not visible in Google.
> 
> Two questions here:
> Are You running in read-only mode?
No.
> Which fields did you actually modify?
Phone, work address, email 

THANKS!!

**Comment by zanonmark** [comment]
Thanks for updating Your report.

I strongly suspect all these tree bugs are related.
As I said, I myself experienced the first one.

So, I'm investigating and (hopefully) providing a fix in a few days.

Thanks,
MZ

**Comment by saleslogistix** [comment]
OH have I got a happy update for you!!!!
Just did some quick experimentation, and the bugs are definitely related and "easily" fixed.
When you create a new account to sync, the default is read-only.  That's probably the right thing to do, for safety.
But when you look in the TBsync Account manager's Account Settings tab, the check-box for Read-only does NOT reflect this status, and if you check/uncheck the box, it does NOT change the status. So, the sync is "doing what it should do" but the fact that you can't see that it's in read-only mode (and you can't un-set it) is a problem...but that's almost entirely a UI problem, rather than something wrong with the algorithm.
So for me, the work-around is to re-create the accounts for synching with the Read-only checkbox un-checked.
Then, all three of these bugs seems to disappear.
Unfortunately, it also means that any changes I've made to the local addressbook are lost...but they were going to be lost on the next sync anyway.
NOTE that the first bug goes away when you get out of read-only mode...but in read-only mode, that clear-on-second-sync behavior shouldn't have occurred...so it's still a bug, but much lower priority IMHO.

**Comment by zanonmark** [comment]
Fixed the UI bugs too.
Could You please check the current version in the repository and confirm the bugs are all gone?

Thanks,
MZ

**Comment by zanonmark** [comment]
Well, try now please, I just fixed another 3-4 bugs... :)

MZ

**Comment by saleslogistix** [comment]
The original bug #1 is resolved both for read-only and read-write mode.
(more to come in a second)

**Comment by saleslogistix** [comment]
Used your "latest" ZIP file as testbed, in Debug Add-On mode
Bug #1 -- disappearing list members -- appears to be fixed just fine.
Bugs #2 and 3 -- the UI does not reflect or control read only status -- NOT fixed.

**Comment by zanonmark** [comment]
> Bugs #2 and 3 -- the UI does not reflect or control read only status -- NOT fixed.

Well, it seems to be fixed in my installation.
Could You please delete and recreate the account? It should work then.

Thanks,
MZ

**Comment by saleslogistix** [comment]
Deleted that addressbook.
Created new one in default (read-only) mode.
Now the check-box DOES show read-only.  Yay.
De-activated that sync so I could un-check the box, did that and re-activated.
That sync shows as NOT read-only, but in fact it is still in that mode.  So the check-box is not always showing the actual mode and is not controlling it either.

**Comment by zanonmark** [comment]
Ok, this took forever to track down!

Fixed now in the current tree. Could You please download the latest and test? (Delete and recreate the account first.)

Thanks,
MZ

**Comment by saleslogistix** [comment]
OK, seems to work fine.  We can close all three of these bugs.
NOTE that now the new-account-creation cycle for synching no longer defaults to Read only.
Looks like full write synching is working for me now.
Thanks

**Comment by zanonmark** [comment]
> OK, seems to work fine. We can close all three of these bugs.

Thanks for confirming.

> NOTE that now the new-account-creation cycle for synching no longer defaults to Read only.

Thanks, fixed right now.

> Looks like full write synching is working for me now.

It works, except that modifications (additions / removals) of contacts to mailing-lists are not reflected back to Google. I can't fix it now, I'm waiting for the new underlying TbSync layer.

Thanks,
MZ

**Comment by saleslogistix** [comment]
Please let me know when the new xpi is available...thx!

**Comment by zanonmark** [comment]
Available since yesterday (0.1.4).

Thanks for debugging,
MZ

**Comment by saleslogistix** [comment]
Are you kidding?  YOU did all the hard work.  
Thanks for producing this much-needed plugin!
